#!/bin/bash

function init1()
{
	src="asm_src/message.asm"
	obj="asm_src/message.o"
	def="MESSAGE"
	size="# define MSIZE"
}

function init2()
{
	src="asm_src/prep.asm"
	obj="asm_src/prep.o"
	def="PREP"
	size="# define PSIZE"
}

function init3()
{
	src="asm_src/rc4.asm"
	obj="asm_src/rc4.o"
	def="RC4"
	size="# define RSIZE"
}

function init4()
{
	src="asm_src/end.asm"
	obj="asm_src/end.o"
	def="END"
	size="# define ESIZE"
}

#inc="include/woody.h"
function update()
{
	inc=include/woody.h
	shellcode=""
	nasm -felf64 $src
	for i in $(objdump -d $obj | grep "^ "| cut -f2)
	do
		shellcode="$shellcode$i"
	done
	shellsize=$(for i in $(objdump -d $obj | grep "^ "| cut -f2); do echo $i; done | wc -l)
    if ! grep -q "$def \"$shellcode\"" $inc; then
            sed -i "s/$def.*/$def \"${shellcode}\"/" $inc
    fi

    if ! grep -q "$size ${shellsize}" $inc; then
            sed -i "s/$size.*/$size ${shellsize}/" $inc
    fi
	#sed -i "s/$def.*/$def \"${shellcode}\"/" $inc
	#sed -i "s/$size.*/$size ${shellsize}/" $inc
}

if [ $# -ne 0 ]
then
	init$1
	update
else
	echo " --- Update all shellcode ---"
	for i in {1..4}
	do
		init$i
		update
	done
fi
